# Generated by Django 3.0.6 on 2020-05-23 18:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstCharacter',
            fields=[
                ('insert_user', models.CharField(editable=False, max_length=150, verbose_name='登録ユーザー')),
                ('insert_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 3, 40, 8, 872311), editable=False, verbose_name='登録日時')),
                ('insert_prg', models.CharField(blank=True, max_length=150, null=True, verbose_name='登録プログラム')),
                ('update_user', models.CharField(editable=False, max_length=150, verbose_name='更新ユーザー')),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 3, 40, 8, 873308), editable=False, verbose_name='更新日時')),
                ('update_prg', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新プログラム')),
                ('delete_flg', models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='削除フラグ')),
                ('mstcharacter_id', models.AutoField(primary_key=True, serialize=False, verbose_name='キャラクタマスタID')),
                ('character_name', models.CharField(max_length=200, verbose_name='キャラクタ名称')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='画像url')),
            ],
            options={
                'verbose_name': 'キャラクタマスタ',
                'verbose_name_plural': 'キャラクタマスタ',
                'db_table': 'mst_character',
                'ordering': ['mstcharacter_id'],
            },
        ),
        migrations.CreateModel(
            name='MstQuestion',
            fields=[
                ('insert_user', models.CharField(editable=False, max_length=150, verbose_name='登録ユーザー')),
                ('insert_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 3, 40, 8, 872311), editable=False, verbose_name='登録日時')),
                ('insert_prg', models.CharField(blank=True, max_length=150, null=True, verbose_name='登録プログラム')),
                ('update_user', models.CharField(editable=False, max_length=150, verbose_name='更新ユーザー')),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 3, 40, 8, 873308), editable=False, verbose_name='更新日時')),
                ('update_prg', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新プログラム')),
                ('delete_flg', models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='削除フラグ')),
                ('mstquestion_id', models.AutoField(primary_key=True, serialize=False, verbose_name='質問マスタID')),
                ('question_content', models.CharField(max_length=400, verbose_name='質問内容')),
            ],
            options={
                'verbose_name': '質問マスタ',
                'verbose_name_plural': '質問マスタ',
                'db_table': 'mst_question',
                'ordering': ['mstquestion_id'],
            },
        ),
    ]
