# Generated by Django 3.0.6 on 2020-05-24 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinatorapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcharacter',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 43, 49, 45901), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='mstcharacter',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 43, 49, 45901), editable=False, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='mstquestion',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 43, 49, 45901), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='mstquestion',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 43, 49, 45901), editable=False, verbose_name='更新日時'),
        ),
    ]
