# Generated by Django 3.0.6 on 2020-05-24 07:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akinatorapi', '0002_auto_20200524_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcharacter',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 46, 38, 562559), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='mstcharacter',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 46, 38, 562559), editable=False, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='mstquestion',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 46, 38, 562559), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='mstquestion',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 46, 38, 562559), editable=False, verbose_name='更新日時'),
        ),
        migrations.CreateModel(
            name='TblAkinator',
            fields=[
                ('insert_user', models.CharField(editable=False, max_length=150, verbose_name='登録ユーザー')),
                ('insert_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 46, 38, 562559), editable=False, verbose_name='登録日時')),
                ('insert_prg', models.CharField(blank=True, max_length=150, null=True, verbose_name='登録プログラム')),
                ('update_user', models.CharField(editable=False, max_length=150, verbose_name='更新ユーザー')),
                ('update_datetime', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 16, 46, 38, 562559), editable=False, verbose_name='更新日時')),
                ('update_prg', models.CharField(blank=True, max_length=150, null=True, verbose_name='更新プログラム')),
                ('delete_flg', models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='削除フラグ')),
                ('tblakinator_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アキネーターテーブルID')),
                ('yes', models.BigIntegerField(default=0, verbose_name='はい')),
                ('no', models.BigIntegerField(default=0, verbose_name='いいえ')),
                ('donotunderstand', models.BigIntegerField(default=0, verbose_name='分からない')),
                ('maybeyes', models.BigIntegerField(default=0, verbose_name='たぶんそう')),
                ('maydifferent', models.BigIntegerField(default=0, verbose_name='たぶん違う')),
                ('mstchatacter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TblAkinator_mstcharacter', to='akinatorapi.MstCharacter', verbose_name='キャラクタマスタID')),
                ('mstquestion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TblAkinator_mstquestion', to='akinatorapi.MstQuestion', verbose_name='質問マスタID')),
            ],
            options={
                'verbose_name': 'アキネーターテーブル',
                'verbose_name_plural': 'アキネーターテーブル',
                'db_table': 'tbl_akinator',
                'ordering': ['tblakinator_id'],
            },
        ),
    ]
