# Generated by Django 3.0.6 on 2020-05-25 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinatorapi', '0003_auto_20200524_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblakinator',
            old_name='mstchatacter',
            new_name='mstcharacter',
        ),
        migrations.AlterField(
            model_name='mstcharacter',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 21, 9, 14, 533659), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='mstcharacter',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 21, 9, 14, 533659), editable=False, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='mstquestion',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 21, 9, 14, 533659), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='mstquestion',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 21, 9, 14, 533659), editable=False, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='tblakinator',
            name='insert_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 21, 9, 14, 533659), editable=False, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='tblakinator',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 21, 9, 14, 533659), editable=False, verbose_name='更新日時'),
        ),
    ]
